#!/bin/bash
# Generate sdl12_wrapper_fwd.c: a generic forwarder for every SDL_ symbol the
# CSNeo engine + its mods + the cabinet SDL libs need (the union is in $1).
#
# Each symbol is forwarded to the REAL SDL. The real SDL is loaded EXPLICITLY
# by absolute path with dlopen() (see REAL_SDL_PATH below), NOT via
# RTLD_NEXT/NEEDED - the real lib's SONAME still reads libSDL-1.2.so.0 which
# collides with the wrapper's own SONAME, so a NEEDED would be a self-ref.
# An explicit dlopen by path sidesteps the collision and the load-order race.
#
# i386 cdecl passes all args on the stack as 4-byte slots, so a
# (long x6) signature forwards any real signature safely; the (long) return
# covers int/pointer/Uint32.
#
# Usage: gen_sdl_wrapper.sh <symsfile> <out.c> <real_sdl_abs_path>
set -e
SYMFILE="$1"
OUT="$2"
REAL_SDL="${3:-/home/aderumier/code/jurassicpark.wine/drive_c/game/CounterStrike Neo/csneo2/lib/libSDL-1.2.real.so.0}"

{
cat <<EOF
// AUTO-GENERATED by gen_sdl_wrapper.sh - do not edit.
#define _GNU_SOURCE
#include <dlfcn.h>
#include <stdint.h>

static void *_sdl_real_handle(void)
{
    static void *h = 0;
    if (!h) h = dlopen("$REAL_SDL", RTLD_NOW | RTLD_GLOBAL);
    return h;
}
static void *_sdl_real_sym(const char *name)
{
    static void *sym = 0;
    static const char *last = 0;
    // cache: only valid for the most-looked-up name (cheap path); re-resolve
    // otherwise. dlsym on an already-loaded lib is cheap; correctness first.
    (void)last;
    return dlsym(_sdl_real_handle(), name);
}

EOF

while IFS= read -r sym; do
  [ -z "$sym" ] && continue
  # We override SDL_GL_SetAttribute ourselves in sdl12_wrapper.c.
  [ "$sym" = "SDL_GL_SetAttribute" ] && continue
  cat <<EOF
long $sym(long a1, long a2, long a3, long a4, long a5, long a6)
{
    void *p = _sdl_real_sym("$sym");
    if (!p) return 0;
    return ((long(*)(long,long,long,long,long,long))p)(a1,a2,a3,a4,a5,a6);
}
EOF
done < "$SYMFILE"
} > "$OUT"
echo "generated $OUT with $(grep -c '^long SDL_' "$OUT") forwarders"
