#!/usr/bin/env python3
"""Rebuild the import table of a 64-bit Raw Thrills g7 dump (HASP Envelope).

The dump of a running game holds the envelope's decrypted relocation list:
36-byte records (u32 type: 6 GLOB_DAT, 7 JUMP_SLOT, u32 name offset, u32
version offset, u64 slot address, 5 x u32), the offsets into a string block
of "name\\0version\\0" strings. (Read from its slots, a record's type and
names are the 12 bytes before it: the libraries' addresses still in the GOT
group by library only that way.) Every entry whose slot is in the dump's
image (the GOT, and the .got after it, __libc_start_main among them) is
printed as a C table, { slot, name, version }, for the g7 preload.

    g7-imports.py game2 > imports.h

The table is found from the GOT: the longest run of library addresses
(0x7f...) in the data segment; the entries pointing at its first slot, and
the string block from the first entry whose name is a known libc symbol.
"""
import struct
import sys

KNOWN = (b"free", b"malloc", b"realloc", b"memcpy", b"strlen", b"fopen")


def load(path):
    data = open(path, "rb").read()
    (phoff,) = struct.unpack_from("<Q", data, 0x20)
    phentsize, phnum = struct.unpack_from("<HH", data, 0x36)
    segs = []
    for i in range(phnum):
        p_type, _, p_offset, p_vaddr, _, p_filesz = struct.unpack_from("<IIQQQQ", data, phoff + i * phentsize)
        if p_type == 1:  # PT_LOAD
            segs.append((p_vaddr, p_offset, p_filesz))
    return data, segs


def va2off(segs, va):
    for vaddr, off, size in segs:
        if vaddr <= va < vaddr + size:
            return va - vaddr + off
    return None


def cstr(data, off):
    end = data.index(b"\0", off)
    return data[off:end]


def main():
    data, segs = load(sys.argv[1])
    vaddr, off, size = segs[-1]  # the data segment

    # The GOT: the longest run of library addresses.
    best = (0, 0)
    i = off
    while i + 8 <= off + size:
        if 0x7F0000000000 <= struct.unpack_from("<Q", data, i)[0] < 0x800000000000:
            j = i
            while j + 8 <= off + size and 0x7F0000000000 <= struct.unpack_from("<Q", data, j)[0] < 0x800000000000:
                j += 8
            if j - i > best[1] - best[0]:
                best = (i, j)
            i = j
        else:
            i += 8
    got_start = best[0] - off + vaddr
    got_end = best[1] - off + vaddr

    # The relocation list: an entry holding the GOT's first slot.
    def kind(e):  # a record's type, from the address of its slot
        return struct.unpack_from("<I", data, e - 12)[0]

    entry = data.find(struct.pack("<Q", got_start), off, off + size)
    while entry >= 0 and kind(entry) not in (6, 7):
        entry = data.find(struct.pack("<Q", got_start), entry + 1, off + size)
    if entry < 0:
        sys.exit("no relocation entry for the GOT's first slot %#x" % got_start)
    first = entry
    while kind(first - 36) in (1, 5, 6, 7):
        first -= 36

    # The string block, from an entry whose name is a known symbol.
    base = None
    e = first
    while base is None and kind(e) in (1, 5, 6, 7):
        name_off = struct.unpack_from("<I", data, e - 8)[0]
        for known in KNOWN:
            p = data.find(b"\0" + known + b"\0", off, off + size)
            if p >= 0 and p + 1 - name_off >= off:
                cand = p + 1 - name_off
                if all(32 < c < 127 for c in cstr(data, cand + name_off)):
                    base = cand
                    break
        e += 36
    if base is None:
        sys.exit("string block not found")

    print("// Generated by tools/g7-imports.py from %s: GOT %#x..%#x." % (sys.argv[1].split("/")[-1], got_start, got_end))
    print("static const struct { unsigned long slot; const char *name, *version; } imports[] = {")
    e = first
    count = 0
    while kind(e) in (1, 5, 6, 7):
        slot = struct.unpack_from("<Q", data, e)[0]
        name_off, ver_off = struct.unpack_from("<II", data, e - 8)
        # The GOT's slots and the .got's after it (__libc_start_main...).
        if va2off(segs, slot) is not None:
            name = cstr(data, base + name_off).decode()
            version = cstr(data, base + ver_off).decode() if ver_off else ""
            print('    {%#x, "%s", "%s"},' % (slot, name, version))
            count += 1
        e += 36
    print("};")
    print("// %d slots (the GOT has %d)" % (count, (got_end - got_start) // 8), file=sys.stderr)


main()
